### ISSUE TITLE
Is there a way to specify text encoding? (Web API)

### ISSUE THREAD

**Issue by sksmania** [MyScript/iinkJS#12]
Hello,
Is there a way to specify text encoding?

I have input Korean as shown below, the characters are rendered in a empty boxed state. 
ex) editor.import('가나다', 'text/plain')

* I have used Interactive Ink SDK Web API version 1.5

**Comment by mathieuruellan** [comment]
Hello,

We have reproduced this issue. That is a regression. IInkJs doesn't set the right font in the setTheme message.
We will push a fix quickly.

**Comment by sksmania** [comment]
Okay thank you for quick reply.
Have a good day :)

**Comment by mathieuruellan** [comment]
Hello @sksmania . Our team has pushed a new release today, fixing this issue.
Don't hesitate to add a feedback.
