### ISSUE TITLE
Feature Request: MathML import for Math blocks

### ISSUE THREAD

**Issue by JayAndBee** [MyScript/iinkJS#2]
Dear team,

no issue to raise. I am impressed with the progress on iinkJS and I am planning to implement it into my own webapp. I was wondering if you are planning to make MathML an available import feature for Math blocks in the foreseeable future. 

Best,

J&B

**Comment by MyScriptSupport** [comment]
Dear J&B,

Thank you for your feedback on our technology.

For the moment, there is no MathML import feature planned in our future release. We have nevertheless  taken note of your suggestion.

Best,

The MyScript Support team.
