### ISSUE TITLE
what i missing here?

### ISSUE THREAD

**Issue by johnfelipe** [MyScript/iinkJS#9]
apt update
    apt upgrade
    shutdown -r now
    
    apt install git python3-pip
    sudo apt install curl
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt update && sudo apt install yarn
    
    
    apt install npm
    git clone https://github.com/MyScript/iinkJS.git
    cd iinkJS
    npm install
    npm audit fix
    
    npm run build
    npm run dev

and logs show this

    http://localhost:8080 -> /root/iinkJS
    LiveReload enabled
    (!) Circular dependencies
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/select.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/selectAll.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/filter.js -> node_modules/d3-selection/src/selection/index.js
    ...and 9 more
    created dist/iink.min.js in 6.2s
    bundles src/iink.js → dist/iink.esm.js...
    (!) Circular dependencies
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/select.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/selectAll.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/filter.js -> node_modules/d3-selection/src/selection/index.js
    ...and 9 more
    created dist/iink.esm.js in 5.1s
    
    [2021-06-16 20:47:33] waiting for changes...
    
How can deploy in public ip?

**Comment by johnfelipe** [comment]
i put this:

HOST=192.241.157.105 npm run dev

    root@one-ubuntu-s-8vcpu-16gb-nyc1-01:~/iinkJS# HOST=192.241.157.105 npm run dev
    
    > iink-js@1.4.5 dev /root/iinkJS
    > npm-run-all minify-css dev:js
    
    
    > iink-js@1.4.5 minify-css /root/iinkJS
    > cleancss -o dist/iink.min.css src/*.css
    
    
    > iink-js@1.4.5 dev:js /root/iinkJS
    > rollup -c config/rollup.config.dev.js -w --sourcemap
    rollup v2.18.0
    bundles src/iink.js → dist/iink.min.js...
    http://localhost:8080 -> /root/iinkJS
    LiveReload enabled
    (!) Circular dependencies
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/select.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/selectAll.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/filter.js -> node_modules/d3-selection/src/selection/index.js
    ...and 9 more
    created dist/iink.min.js in 6.5s
    bundles src/iink.js → dist/iink.esm.js...
    (!) Circular dependencies
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/select.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/selectAll.js -> node_modules/d3-selection/src/selection/index.js
    node_modules/d3-selection/src/selection/index.js -> node_modules/d3-selection/src/selection/filter.js -> node_modules/d3-selection/src/selection/index.js
    ...and 9 more
    created dist/iink.esm.js in 5.2s
    
    [2021-06-16 20:52:30] waiting for changes...

still not changes

**Comment by L4ngu0r** [comment]
Hello,

What are you trying to achieve ? Serve examples on a specific address ?

You are running in dev mode, by defaut our configuration is only localhost : https://github.com/MyScript/iinkJS/blob/master/config/rollup.config.dev.js#L10 (If you are not familiar with [rollup](https://github.com/rollup/rollup), please check how it works.)

If you want dev mode to be available on specific ip address, you should change the configuration of `localhost` to `<your-ip>` in `rollup.config.dev.js`.

BUT

The best is to use our npm package [iink-js](https://www.npmjs.com/package/iink-js) in your own project, by creating an html file that you will serve from a simple http serve. You can get more information here : https://developer.myscript.com/docs/interactive-ink/1.4/web/iinkjs/get-started/

**Comment by johnfelipe** [comment]
Yes I want deploy examples in a public IP
Then change that line and execute normally?

**Comment by L4ngu0r** [comment]
Hello,

Did you solve your problem?
